# .github/workflows/ci.yml

name: QA Automation CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
        browser: [chrome, firefox]

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # 3️⃣ Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install selenium webdriver-manager pytest-html

      # 4️⃣ Install browsers and dependencies
      - name: Install browsers and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget xvfb libgtk-3-0 libdbus-glib-1-2 libasound2

          # Install Chrome
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

          # Install Firefox manually
          wget https://ftp.mozilla.org/pub/firefox/releases/123.0/linux-x86_64/en-US/firefox-123.0.tar.bz2
          tar xjf firefox-123.0.tar.bz2
          sudo mv firefox /opt/firefox
          sudo ln -sf /opt/firefox/firefox /usr/bin/firefox

      # 5️⃣ Run tests (use xvfb-run for Firefox headless stability)
      - name: Run tests
        run: |
          if [ "${{ matrix.browser }}" == "firefox" ]; then
            xvfb-run -a pytest -m e2e --browser ${{ matrix.browser }} --headless --html=reports/report_${{ matrix.browser }}.html --self-contained-html
          else
            pytest -m e2e --browser ${{ matrix.browser }} --headless --html=reports/report_${{ matrix.browser }}.html --self-contained-html
          fi

      # 6️⃣ Upload HTML reports as artifacts
      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: reports/*.html
# name: Name of your workflow.

# on.push: Trigger workflow when someone pushes to main.

# on.pull_request: Trigger workflow when a PR targets main.

# matrix: Runs the job multiple times for each combination (Python 3.11 + chrome, Python 3.11 + firefox).

# runs-on: GitHub runner OS (Ubuntu recommended).

# actions/checkout@v3: Checks out your code.

# actions/setup-python@v5: Sets Python version on runner.
# actions/upload-artifact@v3: GitHub Action to save files (like reports).

# path: Folder containing HTML reports.

