# .github\workflows\ci.yml

name: QA Automation CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
        browser: [chrome, firefox]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install selenium webdriver-manager pytest-html

      # - name: Install browsers
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y chromium-browser chromium-chromedriver firefox

      # - name: Install Chrome and Firefox
      #   run: |
      #     wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      #     sudo apt install -y ./google-chrome-stable_current_amd64.deb
      #     sudo apt install -y firefox
      - name: Install browsers
        run: |
          sudo apt-get update
          sudo apt-get install -y wget xvfb libgtk-3-0 libdbus-glib-1-2

          # Install Chrome
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

          # Install Firefox manually
          wget https://ftp.mozilla.org/pub/firefox/releases/123.0/linux-x86_64/en-US/firefox-123.0.tar.bz2
          tar xjf firefox-123.0.tar.bz2
          sudo mv firefox /opt/firefox
          sudo ln -sf /opt/firefox/firefox /usr/bin/firefox

      - name: Run tests
        run: |
          pytest -m e2e --browser ${{ matrix.browser }} --headless --html=reports/report_${{ matrix.browser }}.html --self-contained-html

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: html-report-${{ matrix.browser }}
          path: reports/*.html
# name: Name of your workflow.

# on.push: Trigger workflow when someone pushes to main.

# on.pull_request: Trigger workflow when a PR targets main.

# matrix: Runs the job multiple times for each combination (Python 3.11 + chrome, Python 3.11 + firefox).

# runs-on: GitHub runner OS (Ubuntu recommended).

# actions/checkout@v3: Checks out your code.

# actions/setup-python@v5: Sets Python version on runner.
# actions/upload-artifact@v3: GitHub Action to save files (like reports).

# path: Folder containing HTML reports.

