name: QA Automation CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# name: Name of your workflow.

# on.push: Trigger workflow when someone pushes to main.

# on.pull_request: Trigger workflow when a PR targets main.

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
        browser: [chrome, firefox]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # matrix: Runs the job multiple times for each combination (Python 3.11 + chrome, Python 3.11 + firefox).

      # runs-on: GitHub runner OS (Ubuntu recommended).

      # actions/checkout@v3: Checks out your code.

      # actions/setup-python@v5: Sets Python version on runner.

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          mkdir -p reports
          pytest -m e2e --headless --browser ${{ matrix.browser }} --html=reports/report_${{ matrix.browser }}.html

      - name: Upload HTML reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: reports/
# actions/upload-artifact@v3: GitHub Action to save files (like reports).

# path: Folder containing HTML reports.

